version: "3.9"
services:
  pg:
    image: postgres
    volumes:
      - ./tmp/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/map-near-places
      - bundler_gems:/user/local/bundle/
    ports:
      - "3000:3000"
    depends_on:
      - pg
volumes: 
    postgres:
    bundler_gems: